version: '3.1'
services:
  web:
    build: .
    container_name: php-apache-web
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./htdocs/:/var/www/html/
    depends_on:
      - phpmyadmin
      - db
  db:
    image: mysql:latest
    container_name: php-apache-mysql
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-apache-admin
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    depends_on:
      - db
    ports:
      - 8887:80
  